README.md
=> ReadMe update.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/QueryableExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, AutoMapper.OData.EFCore.Tests/Mappings/CoreBuildingMappings.cs, Directory.Build.props
Replacing IIncludableQueryable includes in favour of selectors  for ProjectTo in EFCore.
=> Replace IIncludableQueryable includes in favour of selectors  for ProjectTo in EFCore.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/QueryableExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, AutoMapper.OData.EFCore.Tests/Mappings/CoreBuildingMappings.cs, Directory.Build.props, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Updating the web projects to use the latest libraries
=> Updating the web projects to use the latest libraries

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/QueryableExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/TypeExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/Mappings/CoreBuildingMappings.cs, AutoMapper.OData.EFCore.Tests/Mappings/OpsTenantMappings.cs, Directory.Build.props, WebAPI.AspNet.OData.EF6/Mappings/CoreBuildingMappings.cs, WebAPI.AspNet.OData.EF6/Mappings/OpsTenantMappings.cs, WebAPI.AspNetCore.OData.EF6/Controllers/OpsTenantController.cs, WebAPI.AspNetCore.OData.EF6/Mappings/CoreBuildingMappings.cs, WebAPI.AspNetCore.OData.EF6/Mappings/OpsTenantMappings.cs, WebAPI.OData.EFCore/Controllers/OpsTenantController.cs, WebAPI.OData.EFCore/Mappings/CoreBuildingMappings.cs, WebAPI.OData.EFCore/Mappings/OpsTenantMappings.cs
Update to retrieve only the required database columns.
=> Update to retrieve only the required database columns.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, Directory.Build.props, WebAPI.AspNet.OData.EF6/Controllers/OpsTenantController.cs, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Bug fixes for selectors on sub-queries.
=> Bug fixes for selectors on sub-queries.

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Updating sample projects to use latest.
=> Updating sample projects to use latest.

AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/TypeExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, Directory.Build.props, README.md
=> Cleaning up unit tests.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, Directory.Build.props, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Bug fix: Child selectors not included.
=> Bug fix: Child selectors not included.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, Directory.Build.props, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
=> Version 1.0.3

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Updating web projects to reference the latest.
=> Updating web projects to reference the latest.

AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, Directory.Build.props
Fixes Issue 29 ArgumentNullException: "Value cannot be null."
=> Fixes Issue 29 ArgumentNullException: "Value cannot be null."

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Updating version#s for web samples.
=> Updating version#s for web samples.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, Directory.Build.props
Fixes to: 1)Order By Count. 2) Order By Reference/ChildReference/Property.
=> Fixes to: 1)Order By Count. 2) Order By Reference/ChildReference/Property

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, Directory.Build.props
Fix for missing NavigationNode.NavigationSource.Path.PathSegments in web request.
=> Fix for missing NavigationNode.NavigationSource.Path.PathSegments in web request.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.Extensions.OData.sln, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, Directory.Build.props, Web.Tests/GetTests.cs, Web.Tests/Web.Tests.csproj, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
v1.0.5. Adding HttpClient Tests.
=> Adding HttpClient Tests.

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
=> Updating sample projects.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/TypeExtensions.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, Directory.Build.props
Updating libraries to support AutoMapper.Extensions.ExpressionMapping v4 and AutoMapper v10.
=> Updating libraries to support AutoMapper v10

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.AspNetCore.OData.EF6/WebAPI.AspNetCore.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Referencing latest libraries from sample projects.
=> Referencing latest libraries from sample projects.

.github/workflows/ci.yml, .github/workflows/release.yml, AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, Directory.Build.props, Pack_Push.ps1
=> Testing Minver

WebAPI.AspNet.OData.EF6/Controllers/OpsTenantController.cs, WebAPI.AspNet.OData.EF6/Mappings/CoreBuildingMappings.cs, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Update references from myget to nuget.
=> Update references from myget to nuget.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/FilterHelper.cs, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.Extensions.OData.sln, AutoMapper.OData.EFCore.Tests/Data/DataClasses.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, AutoMapper.OData.EFCore.Tests/Model/ModelClasses.cs, DAL.EFCore/MyDbContext.cs, ExpressionBuilder.Tests/Data/DataClasses.cs, ExpressionBuilder.Tests/ExpressionStringBuilder.cs, ExpressionBuilder.Tests/FilterTests.cs, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Using latest expression builder.
=> Using the latest expression builder.

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Samples projects referencing latest.
=> Samples projects referencing latest.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Referencing the latest expression builder.
=> Referencing the latest expression builder.

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
=> Updating references.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/QueryableExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/Visitors/ChildCollectionFilterUpdater.cs, AutoMapper.AspNetCore.OData.EFCore/Visitors/ChildCollectionOrderByUpdater.cs, AutoMapper.AspNetCore.OData.EFCore/Visitors/FilterAppender.cs, AutoMapper.AspNetCore.OData.EFCore/Visitors/MethodAppender.cs, AutoMapper.AspNetCore.OData.EFCore/Visitors/ProjectionVisitor.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, Web.Tests/GetTests.cs
Filtering and sorting child collections in EF6 libraries.
=> Filtering and sorting child collections in EF6 libraries.

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Sample projects referencing latest.
=> Sample projects referencing latest.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, WebAPI.AspNet.OData.EF6/Web.config, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Using Expression Mapping v4.0.2-preview-3.
=> Using Expression Mapping v4.0.2-preview-3.

.github/workflows/ci.yml, .github/workflows/release.yml, AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, WebAPI.AspNet.OData.EF6/Web.config, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
v.latest from AutoMapper.Extensions.ExpressionMapping
=> v.latest from AutoMapper.Extensions.ExpressionMapping

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Sample projects referencing v2.0.2
=> Sample projects referencing v2.0.2

WebAPI.AspNet.OData.EF6/Controllers/OpsTenantController.cs
Fixing GetQueryAsync in controller.
=> Fixing GetQueryAsync in controller.

AutoMapper.AspNetCore.OData.EFCore/Visitors/ProjectionVisitor.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs
=> Make expansion name testing against the binding name case insensitive.

MigrationTool/MigrationContext.cs, SeedDatabase/appsettings.json, WebAPI.AspNet.OData.EF6/App_Start/WebApiConfig.cs, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj, WebAPI.OData.EFCore/appsettings.json
=> Sample projects to latest.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/QueryableExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/ODataSettings.cs, AutoMapper.AspNetCore.OData.EFCore/QuerySettings.cs, AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs, AutoMapper.Extensions.OData.sln, AutoMapper.OData.EF6.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EF6.Tests/GetQueryTests.cs, AutoMapper.OData.EF6.Tests/GetTests.cs, AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, WebAPI.AspNet.OData.EF6/Controllers/OpsTenantController.cs, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EF6/Controllers/OpsTenantController.cs, WebAPI.OData.EF6/WebAPI.OData.EF6.csproj, WebAPI.OData.EFCore/Controllers/OpsTenantController.cs, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
=> Refactoring QuerySettings.

AutoMapper.OData.EF6.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/Data/DatabaseInitializer.cs, AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, DAL.EF6/TMandator.cs, DAL.EFCore/TMandator.cs, DAL/TMandator.cs, Domain.OData/OpsTenant.cs, Domain/OpsTenant.cs, MigrationTool/Migrations/20201204103827_CreatedDate.Designer.cs, MigrationTool/Migrations/20201204103827_CreatedDate.cs, SeedDatabase/Program.cs, Web.Tests/GetTests.cs, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.AspNet.OData.EF6/packages.config, WebAPI.OData.EF6/WebAPI.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
=> DateTime filter tests.

WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.OData.EF6/WebAPI.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Sample projects referencing latest nuget packages.
=> Sample projects referencing latest nuget packages.

AutoMapper.AspNet.OData.EF6/AutoMapper.AspNet.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.OData.EF6.Tests/AutoMapper.OData.EF6.Tests.csproj, AutoMapper.OData.EF6.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EF6.Tests/GetQueryTests.cs, AutoMapper.OData.EF6.Tests/GetTests.cs, AutoMapper.OData.EFCore.Tests/AutoMapper.OData.EFCore.Tests.csproj, AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, ExpressionBuilder.Tests/ExpressionBuilder.Tests.csproj, ExpressionBuilder.Tests/FilterTests.cs, Web.Tests/GetTests.cs, Web.Tests/Web.Tests.csproj, WebAPI.AspNet.OData.EF6/WebAPI.AspNet.OData.EF6.csproj, WebAPI.OData.EF6/Properties/launchSettings.json, WebAPI.OData.EF6/Startup.cs, WebAPI.OData.EF6/WebAPI.OData.EF6.csproj, WebAPI.OData.EFCore/Startup.cs, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Supporting Microsoft.AspNetCore.OData v8.0.1
=> Microsoft.AspNetCore.OData v8.0.1

.github/workflows/ci.yml, .github/workflows/release.yml, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EF6/QueryableExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/ODataSettings.cs, AutoMapper.AspNetCore.OData.EFCore/Properties/Resources.Designer.cs, AutoMapper.AspNetCore.OData.EFCore/QueryableExtensions.cs, AutoMapper.OData.EF6.Tests/AutoMapper.OData.EF6.Tests.csproj, AutoMapper.OData.EFCore.Tests/AutoMapper.OData.EFCore.Tests.csproj, ExpressionBuilder.Tests/ExpressionBuilder.Tests.csproj, WebAPI.OData.EF6/WebAPI.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
Mapping EntityFrameworkCore version to framework version.
=> Mapping EntityFrameworkCore version to framework version.

AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, DAL.EFCore/DAL.EFCore.csproj, SeedDatabase/SeedDatabase.csproj, WebAPI.OData.EF6/WebAPI.OData.EF6.csproj, WebAPI.OData.EFCore/WebAPI.OData.EFCore.csproj
=> .Net6 web sample projects.

AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.OData.EF6.Tests/GetQueryTests.cs, AutoMapper.OData.EF6.Tests/GetTests.cs, Web.Tests/GetTests.cs
Web and EF6 tests for $orderby filtered count.
=> Web and EF6 tests for $orderby filtered count.

AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, Domain.OData/CoreBuilding.cs, Domain.OData/OpsBuilder.cs, Domain.OData/OpsCity.cs, Domain.OData/OpsTenant.cs
Fixes Issue #132 : Inherited DTO properties appear to be ignored.
=> Fixes Issue #132 : Inherited DTO properties appear to be ignored.

AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/Constants.cs, AutoMapper.AspNetCore.OData.EFCore/FilterHelper.cs, ExpressionBuilder.Tests/Data/DataClasses.cs, ExpressionBuilder.Tests/ExpressionStringBuilder.cs, ExpressionBuilder.Tests/FilterTests.cs
Supporting System.DateOnly and System.TimeOnly types.
=> Supporting System.DateOnly and System.TimeOnly types.

AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/FilterHelper.cs, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/ODataQueryContextExtentions.cs, AutoMapper.AspNetCore.OData.EFCore/TypeExtensions.cs, AutoMapper.AspNetCore.OData.EFCore/Visitors/ChildCollectionFilterUpdater.cs, AutoMapper.AspNetCore.OData.EFCore/Visitors/FilterAppender.cs, AutoMapper.OData.EF6.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EF6.Tests/GetQueryTests.cs, AutoMapper.OData.EF6.Tests/GetTests.cs, AutoMapper.OData.EFCore.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, ExpressionBuilder.Tests/FilterTests.cs, ExpressionBuilder.Tests/ODataHelpers.cs, WebAPI.OData.EF6/Startup.cs, WebAPI.OData.EFCore/Startup.cs
Fixing issues #149 and #152 - errors using custom namespace.
=> Fixing issues #149 and #152 - errors using custom namespace.

AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj
Package release notes - Supporting custom namespaces.
=> Package release notes - Supporting custom namespaces.

AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj
=> AutoMapper v12.

AutoMapper.AspNetCore.OData.EFCore/FilterHelper.cs, AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs, AutoMapper.OData.EF6.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, ExpressionBuilder.Tests/FilterTests.cs, ExpressionBuilder.Tests/ODataHelpers.cs
=> Adds support for the $this literal

AutoMapper.AspNetCore.OData.EFCore/Constants.cs, AutoMapper.AspNetCore.OData.EFCore/FilterHelper.cs, DAL.EFCore/DAL.EFCore.csproj, MigrationTool/MigrationTool.csproj, MigrationTool/Migrations/20200918094359_initial.Designer.cs, MigrationTool/Migrations/20200918094359_initial.cs, SeedDatabase/SeedDatabase.csproj
Removing references to net5.0.
=> Removing references to net5.0.

.github/workflows/ci.yml, .github/workflows/release.yml, AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.OData.EF6.Tests/AutoMapper.OData.EF6.Tests.csproj, AutoMapper.OData.EFCore.Tests/AutoMapper.OData.EFCore.Tests.csproj, DAL.EFCore/DAL.EFCore.csproj, ExpressionBuilder.Tests/ExpressionBuilder.Tests.csproj, MigrationTool/MigrationTool.csproj, SeedDatabase/SeedDatabase.csproj
- Updated project to support .net 8 and Efcore 8.
- Updated release to build using 8.x
=> .net 8 support

AutoMapper.OData.EF6.Tests/GetQuerySelectTests.cs, AutoMapper.OData.EF6.Tests/GetQueryTests.cs, AutoMapper.OData.EF6.Tests/GetTests.cs, Web.Tests/GetTests.cs
When I opened the solution I saw that there were some warnings from XUnit. I fixed them.
=> Fix XUnit warnings

AutoMapper.AspNetCore.OData.EFCore/LinqExtensions.cs
=> Fixing build warning CS8632.

AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/Visitors/ProjectionVisitor.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, AutoMapper.OData.EFCore.Tests/Mappings/ObjectMappings.cs, AutoMapper.OData.EFCore.Tests/Model/ModelClasses.cs
=> AutoMapper v14

AutoMapper.AspNetCore.OData.EF6/AutoMapper.AspNetCore.OData.EF6.csproj, AutoMapper.AspNetCore.OData.EFCore/AutoMapper.AspNetCore.OData.EFCore.csproj, AutoMapper.AspNetCore.OData.EFCore/Visitors/ProjectionVisitor.cs, AutoMapper.OData.EFCore.Tests/GetQueryTests.cs, AutoMapper.OData.EFCore.Tests/GetTests.cs, AutoMapper.OData.EFCore.Tests/Mappings/ObjectMappings.cs, AutoMapper.OData.EFCore.Tests/Model/ModelClasses.cs
=> Fixing package release notes
